language: ruby
rvm:
- 2.2.5
deploy:
  provider: heroku
  api_key:
    secure: dbVrZ34DCejs/OE1knvihyWAWtBBNp4L4NhQrPlZvhhbJaPJ13pJQGwRhQpl3BUB8CjK58gMJj74yuPrAHH808lQUB57Zz/tq4J6mnp+rM0A+7IFVah/qjPT6gCrfibVapGjp69XYUrGl0OPnuSsX/OY3HQVS03gbxpnBi9Q8+7M/QB1or4+YgTazRt9ni0oIQaQtI/COmtp9fzhl9MxbHSyUIfRNekOMmiqTIwvDv+WRgyora1KU/3VWenMfaBKFfwgjfga2G++42+zaiwXXyQjJ0jr9KkhS0r6XvaYOmFfcUTwvQwfC2DBR2X9kDuXstgD2nGSTaFbsMN9G9TcDlEXt7iIRV70j7aOZkMts9cSGjxL4vcouen2KffgfXoykjEXtmDvkJtGshye7XpKBLltf9ck0ODWVHZZQBLucUvuUK9KsmnWKmD3A4gUYoRAqU94gL7t3Q5SooAs2T5pXVvir5gw/zLLSmS7EkgXd+RZFYuu3ebahT/GnjIcahlDRGert/py3KgIuxQ0/wboZWX4km3UAiqtZRmMqAVIhe70N7KyOqKmF/KnMCYRyRjA1yTBEmggSAg8adepOsQ++VPVS8CVeCjn0sKwOJ58sIYyJTakqXs4Wb34M0HvbHhoJi3wlu2XQzANf6MW8RTmDZSvMEDJVPTdeNwtr2UvEXQ=
  app: fast-tundra-33061
  on:
    repo: HirokiTakenaka/rakuten_enpit_example
